version: '2'
services:
  notebook:
    build:
      context: .
      # args:
        # GRAPHLAB_LICENSE: ${GLCREATE_PRODUCT_KEY}
    ports:
      - "localhost:8888:8888"
    volumes:
      - ./:/home/jovyan/work
      - ./mlsl:/home/jovyan/mlsl
    restart: "unless-stopped"
    command: start-notebook.sh

  beaker:
    image: beakernotebook/beaker
    volumes:
      - ./:/home/beaker/notebooks
    ports:
      - "8800:8800"
